---
farm_types:
- Farm
- Agriculture
- Acres
- Plantation
- Fields
- Ranch
- Farmstead
- Gardens
- Creek
- Ridge
- Harvests
- Croft
- Grange
- Knolls
- Homestead
level_names:
- Field Hand
- Kinder
- Amateur
- Able
- Handy
- Nimble
- Savvy
- Fancy
- Sophisticated
- Splendid
- Magician
- Wizard
- Jolly Rancher
- Produce Professional
- Professor of Agriculture
- Hot Shot
- Super Shoveler
- Super Grower
- Professional Plower
- Green Giant
- Rockstar
- Barnyard Behemoth
- Magnificent
- Cream of the Crop
- Sensational Sower
- Sultan of Soil
- Thrill of the Till
- Pasture
- Sensation
- Lord of the Plow
- Bastillion of the Barn
- Ace of Acreage
- Livestock Lord
- Practiced
- Skilled
- Green Ribbon
- Clever
- Great
- Smart
- Model
- Frugal
- Hot Shot
- Proficient
- Sophisticated
- Accomplished
- Brilliant
- Prominent
- Expert
- Genius
- Big League
- Master
- Grand Master
- Yellow Ribbon
- Farmer Cashcrop
- The Real Deal
- "Farm-o-saurus Rex"
- White Ribbon
- Can Haz
- "Old Mc-Who"
- Educated
- Red Ribbon
- Hay Roller
- Virtuoso
- Blue Ribbon
- Purple Ribbon
- County Fair Champ
- State Fair Champ
- World Fair Champ
- Beyond Fairs
- Formal
- Livestock
- Tractor
- Market
- Talk of the Town
- "Plant's Best Friend"
- Cow Whisperer
- Farm Hero
- Farm Idol
- Agriculture Aficionado
- Soil Sage
- Crop Connoisseur
- Dirt Disciple
- "Big Ole' Boss"
- Farm Fiend
- Plow Plant Reap Repeater
- High Harvester
- Farm Freak
- Veni Vidi Agri
- Incomparable
- Soil Savant
- Overlord
- Stellar
- Transcendent Tiller
- Universal
- Paragon
- Epic
- Omnipotent Agriculturalist